"""migration

Revision ID: a29788b71802
Revises: 8c39f2a3ea0d
Create Date: 2025-03-14 21:03:22.284075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a29788b71802'
down_revision: Union[str, None] = '8c39f2a3ea0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('vtype', sa.String(), nullable=False))
    op.drop_column('vehicle', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('vehicle', 'vtype')
    # ### end Alembic commands ###
